/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_com_protowork_engine_ImageProcessThread */

#ifndef _Included_br_com_protowork_engine_ImageProcessThread
#define _Included_br_com_protowork_engine_ImageProcessThread
#ifdef __cplusplus
extern "C" {
#endif
#undef br_com_protowork_engine_ImageProcessThread_MIN_PRIORITY
#define br_com_protowork_engine_ImageProcessThread_MIN_PRIORITY 1L
#undef br_com_protowork_engine_ImageProcessThread_NORM_PRIORITY
#define br_com_protowork_engine_ImageProcessThread_NORM_PRIORITY 5L
#undef br_com_protowork_engine_ImageProcessThread_MAX_PRIORITY
#define br_com_protowork_engine_ImageProcessThread_MAX_PRIORITY 10L
#undef br_com_protowork_engine_ImageProcessThread_SERVICE_PROCESS_IMAGE
#define br_com_protowork_engine_ImageProcessThread_SERVICE_PROCESS_IMAGE 65L
#undef br_com_protowork_engine_ImageProcessThread_SERVICE_CREATE_REGION
#define br_com_protowork_engine_ImageProcessThread_SERVICE_CREATE_REGION 66L
#undef br_com_protowork_engine_ImageProcessThread_SERVICE_PREVIEW_VIDEO
#define br_com_protowork_engine_ImageProcessThread_SERVICE_PREVIEW_VIDEO 67L
#undef br_com_protowork_engine_ImageProcessThread_SERVICE_VISUALIZATION_IMAGE_WINDOW
#define br_com_protowork_engine_ImageProcessThread_SERVICE_VISUALIZATION_IMAGE_WINDOW 69L
#undef br_com_protowork_engine_ImageProcessThread_SERVICE_CREATE_DATABASE_TRAINNING
#define br_com_protowork_engine_ImageProcessThread_SERVICE_CREATE_DATABASE_TRAINNING 68L
#undef br_com_protowork_engine_ImageProcessThread_INVALID_VALUE
#define br_com_protowork_engine_ImageProcessThread_INVALID_VALUE -9999L
/*
 * Class:     br_com_protowork_engine_ImageProcessThread
 * Method:    processImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_br_com_protowork_engine_ImageProcessThread_processImage
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     br_com_protowork_engine_ImageProcessThread
 * Method:    createRegions
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_com_protowork_engine_ImageProcessThread_createRegions
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     br_com_protowork_engine_ImageProcessThread
 * Method:    previewRegions
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_br_com_protowork_engine_ImageProcessThread_previewRegions
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     br_com_protowork_engine_ImageProcessThread
 * Method:    databaseTrainning
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_br_com_protowork_engine_ImageProcessThread_databaseTrainning
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     br_com_protowork_engine_ImageProcessThread
 * Method:    showWindowProcessImage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_com_protowork_engine_ImageProcessThread_showWindowProcessImage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
