/*
#  BEAA - Behavior Animal Analyzer - Analisador de comportamento animal
#  Copyright 2019: Richard William Valdivia
#  E-mail: rwvaldivia@yahoo.com.br
#  
#  Este programa é um software livre; você pode redistribui-lo e/ou 
#  modifica-lo dentro dos termos da Licença Pública Geral GNU como 
#  publicada pela Fundação do Software Livre (FSF); na versão 2 da 
#  Licença, ou (na sua opinião) qualquer versão.
#
#  Este programa é distribuído na esperança que possa ser util, 
#  mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
#  MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
#  Licença Pública Geral GNU para maiores detalhes.
#
#  Você deve ter recebido uma cópia da Licença Pública Geral GNU
#  junto com este programa, se não, escreva para a Fundação do Software
#  Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
*/
package br.com.protowork.gui;

import br.com.protowork.engine.ImageProcess;
import br.com.protowork.message.MessageSelectedRegion;
import br.com.protowork.util.ConstantsImageProc;
import br.com.protowork.util.StringUtil;
import br.com.protowork.vo.Project;
import br.com.protowork.xml.PresetXmlCreator;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class NewProjectModal extends javax.swing.JDialog {

    private List<MessageSelectedRegion> listRegioes;
    private JFrame observableWindow;
    private static final int PADRAO_SENSIBILIDADE = 15;
    private static final int PADRAO_BLUR = 10;
    /**
     * Creates new form NewProjectModal
     */
    public NewProjectModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.sliderSensibilidade.setValue(15);
        this.sliderBlur.setValue(10);
        this.lblSensibilidadeValue.setText(String.valueOf(NewProjectModal.PADRAO_SENSIBILIDADE));
        this.lblBlurValue.setText(String.valueOf(NewProjectModal.PADRAO_BLUR));
    }
    
    public void setObservableWindow(JFrame frame){
        this.observableWindow = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtGroupTipoSelecao = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        jblProjeto = new javax.swing.JLabel();
        tfNomeProjeto = new javax.swing.JTextField();
        btnCriar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblBlur = new javax.swing.JLabel();
        lblSensibilidade = new javax.swing.JLabel();
        sliderSensibilidade = new javax.swing.JSlider();
        sliderBlur = new javax.swing.JSlider();
        lblSensibilidadeValue = new javax.swing.JLabel();
        lblBlurValue = new javax.swing.JLabel();
        btnPadrao = new javax.swing.JButton();
        rbtNornalBased = new javax.swing.JRadioButton();
        rbtTopBased = new javax.swing.JRadioButton();
        txtComprimento = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblVideo = new javax.swing.JLabel();
        tfVideoFilename = new javax.swing.JTextField();
        btnSelecionarVideo = new javax.swing.JButton();
        lblCaminhoCompleto = new javax.swing.JLabel();
        btnSelecionarRegioes = new javax.swing.JButton();
        lblRegioes = new javax.swing.JLabel();
        lblRegioesTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Novo projeto");

        jblProjeto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblProjeto.setText("Nome do Projeto:");

        tfNomeProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeProjetoActionPerformed(evt);
            }
        });

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações avançadas"));

        lblBlur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBlur.setText("Blur:");

        lblSensibilidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSensibilidade.setText("Sensibilidade:");

        sliderSensibilidade.setMaximum(40);
        sliderSensibilidade.setMinimum(1);
        sliderSensibilidade.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                listenerSliderHandler(evt);
            }
        });

        sliderBlur.setMaximum(40);
        sliderBlur.setMinimum(1);
        sliderBlur.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                listenerSliderHandler(evt);
            }
        });

        lblSensibilidadeValue.setText("0");

        lblBlurValue.setText("0");

        btnPadrao.setText("Padrão");
        btnPadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadraoActionPerformed(evt);
            }
        });

        rbtGroupTipoSelecao.add(rbtNornalBased);
        rbtNornalBased.setText("Seleção livre");
        rbtNornalBased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNornalBasedActionPerformed(evt);
            }
        });

        rbtGroupTipoSelecao.add(rbtTopBased);
        rbtTopBased.setSelected(true);
        rbtTopBased.setText("Seleção baseado no topo");
        rbtTopBased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTopBasedActionPerformed(evt);
            }
        });

        txtComprimento.setText("47");
        txtComprimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComprimentoActionPerformed(evt);
            }
        });

        txtAltura.setText("24");

        jLabel2.setText("Altura: ");

        jLabel3.setText("Comprimento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSensibilidade)
                            .addComponent(lblBlur, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBlurValue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sliderBlur, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSensibilidadeValue, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtTopBased)
                                            .addComponent(rbtNornalBased, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAltura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtComprimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(sliderSensibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderSensibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSensibilidade)
                        .addComponent(lblSensibilidadeValue)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBlur)
                        .addComponent(lblBlurValue))
                    .addComponent(sliderBlur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtTopBased))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtNornalBased)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnPadrao)))
                .addGap(39, 39, 39))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações de Vídeo"));

        lblVideo.setText("Video:");

        tfVideoFilename.setEditable(false);
        tfVideoFilename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVideoFilenameActionPerformed(evt);
            }
        });

        btnSelecionarVideo.setText("Selecionar Vídeo");
        btnSelecionarVideo.setToolTipText("");
        btnSelecionarVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarVideoActionPerformed(evt);
            }
        });

        lblCaminhoCompleto.setText("Vídeo não selecionado");

        btnSelecionarRegioes.setText("Selecionar Regiões");
        btnSelecionarRegioes.setToolTipText("");
        btnSelecionarRegioes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarRegioesActionPerformed(evt);
            }
        });

        lblRegioes.setText("Total de Regiões Selecionadas:");

        lblRegioesTotal.setText("0");

        jLabel1.setText("Tipo de seleção (região)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(lblRegioes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRegioesTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblVideo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfVideoFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCaminhoCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelecionarVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelecionarRegioes, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVideo)
                    .addComponent(tfVideoFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionarVideo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaminhoCompleto)
                    .addComponent(btnSelecionarRegioes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegioes)
                    .addComponent(lblRegioesTotal))
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar)
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jblProjeto)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblProjeto))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeProjetoActionPerformed

    private void tfVideoFilenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVideoFilenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVideoFilenameActionPerformed

    private void btnSelecionarVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarVideoActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser(ConstantsImageProc.PATH_ROOT);
        int option = fc.showOpenDialog(this);

        if (option == JFileChooser.APPROVE_OPTION){
            lblCaminhoCompleto.setText(fc.getSelectedFile().getAbsolutePath());
            
            if (fc.getSelectedFile().getAbsolutePath().length() > ConstantsImageProc.MAX_FILE_AND_PATH_SIZE){
                JOptionPane.showMessageDialog(null, "Caminho ou nome de arquivo muito grande\nTente mover os arquivos de vídeo para um caminho mais curto");
                tfVideoFilename.setText("");
                lblCaminhoCompleto.setText("Vídeo não selecionado");
                return;
            }
            tfVideoFilename.setText(fc.getSelectedFile().getName());
        } else {
            tfVideoFilename.setText("");
            lblCaminhoCompleto.setText("Vídeo não selecionado");
        }

    }//GEN-LAST:event_btnSelecionarVideoActionPerformed

    private void btnSelecionarRegioesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarRegioesActionPerformed
        
        this.tfVideoFilename.setText(this.tfVideoFilename.getText().trim());
        
        
        String filename = this.tfVideoFilename.getText();
        
        if ("".equals(filename) || !this.helperIsValidFileExtension(filename)){
            JOptionPane.showMessageDialog(null, "Arquivo de video inválido");
            return;
        }
        
        filename = this.lblCaminhoCompleto.getText();
        
        ImageProcess ip = new ImageProcess();
        
        String typeBoxSelection = "";
        int width   = 0;
        int height  = 0;
        if (this.rbtNornalBased.isSelected()){
            typeBoxSelection = ConstantsImageProc.TYPE_BOX_SELECTION_NORMAL;
        } else if (this.rbtTopBased.isSelected()){
            String temp = "";
            typeBoxSelection = ConstantsImageProc.TYPE_BOX_SELECTION_TOP;
            
            temp = StringUtil.letOnlyNumber(this.txtComprimento.getText());
            if (!"".equals(temp)){
                width = Integer.parseInt(temp);
            } else {
                width = Integer.parseInt(ConstantsImageProc.DEFAULT_VALUE_SELECTION_BOX_WIDTH);
            }
            
            temp = StringUtil.letOnlyNumber(this.txtAltura.getText());
            if (!"".equals(temp)){
                height = Integer.parseInt(temp);
            } else {
                height = Integer.parseInt(ConstantsImageProc.DEFAULT_VALUE_SELECTION_BOX_HEIGHT);;
            }
            
        }
        
        this.txtComprimento.setText(String.valueOf(width));
        this.txtAltura.setText(String.valueOf(height));
        
        this.listRegioes = ip.selectRegions(filename, typeBoxSelection, width, height);
        int totReg = 0;
        if (this.listRegioes != null){
            totReg = listRegioes.size();
        } 
        this.lblRegioesTotal.setText(String.valueOf(totReg));
    }//GEN-LAST:event_btnSelecionarRegioesActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        // TODO add your handling code here:
        String temp = "";
        Project project = new Project();
        
        this.tfNomeProjeto.setText(tfNomeProjeto.getText().trim());
        
        
        if ("".equals(this.tfNomeProjeto.getText())){
            temp += "Preencha o campo Nome do Projeto\n";
        }
        
        this.tfVideoFilename.setText(tfVideoFilename.getText().trim());
        
        if("".equals(this.tfVideoFilename.getText())){
            temp += "Selecione um vídeo para processamento\n";
        } else if (!this.helperIsValidFileExtension(this.tfVideoFilename.getText())){
            temp += "Arquivo de video inválido\n";
        }
        
        if (this.listRegioes == null || this.listRegioes.isEmpty()){
            temp += "Selecione regiões no video para serem analisadas\n";
        }
        
        if (!"".equals(temp)){
            JOptionPane.showMessageDialog(null, temp);
            return;
        }
        
        project.setProjectName(this.tfNomeProjeto.getText());
        project.setVideoFileName( this.lblCaminhoCompleto.getText());
        project.setListRegions(listRegioes);
        
        project.setBlurLevel(this.sliderBlur.getValue());
        project.setSensibilityLevel(this.sliderSensibilidade.getValue());
        
        PresetXmlCreator xml = new PresetXmlCreator();
        
        List<Project> list = xml.loadXMLPreset();
        xml.setProjectList(list);
        xml.addProjectFirst(project);
        xml.generateXML();
        
        ImageProcGUI gui = (ImageProcGUI) this.observableWindow;
        gui.updateProjectsTable(list);
        
        if (!(JOptionPane.showConfirmDialog(null, "Projeto Criado!\nDeseja criar um novo Projeto", "Warning",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)){
            this.setVisible(false);
        }
        
        this.helperCleanFields();
    }//GEN-LAST:event_btnCriarActionPerformed
    
    public void helperCleanFields(){
        this.tfNomeProjeto.setText("");
        this.tfVideoFilename.setText("");
        this.lblCaminhoCompleto.setText("Vídeo não selecionado");
        this.lblRegioesTotal.setText("0");
        this.listRegioes = null;
    }
    
    public boolean helperIsValidFileExtension(String st_local){
        
        boolean extensionOk = false;
        int pos = 0;
        if ((pos = st_local.lastIndexOf('.')) == -1){
            return false;
        } else {
            st_local = st_local.substring(pos, st_local.length()).toLowerCase();

            for (int i = 0; i < ConstantsImageProc.VIDEO_FILE_EXTENSION.length; i++){
                if (ConstantsImageProc.VIDEO_FILE_EXTENSION[i].equals(st_local)){
                    extensionOk = true;
                    break;
                }
            }

            if (!extensionOk){
                return false;
            }

        }
        
        return true;
    }
    
    
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.helperCleanFields();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadraoActionPerformed
        // TODO add your handling code here:
        this.lblSensibilidadeValue.setText(String.valueOf(NewProjectModal.PADRAO_SENSIBILIDADE));
        this.lblBlurValue.setText(String.valueOf(NewProjectModal.PADRAO_BLUR));
        this.sliderBlur.setValue(NewProjectModal.PADRAO_BLUR);
        this.sliderSensibilidade.setValue(NewProjectModal.PADRAO_SENSIBILIDADE);
        this.txtAltura.setText(ConstantsImageProc.DEFAULT_VALUE_SELECTION_BOX_HEIGHT);
        this.txtComprimento.setText(ConstantsImageProc.DEFAULT_VALUE_SELECTION_BOX_WIDTH);
        this.helperCleanFields();
    }//GEN-LAST:event_btnPadraoActionPerformed

    private void listenerSliderHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listenerSliderHandler
        // TODO add your handling code here:
        this.lblBlurValue.setText(String.valueOf(this.sliderBlur.getValue()));
        this.lblSensibilidadeValue.setText(String.valueOf(this.sliderSensibilidade.getValue()));
    }//GEN-LAST:event_listenerSliderHandler

    private void txtComprimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComprimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComprimentoActionPerformed

    private void rbtTopBasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTopBasedActionPerformed
        // TODO add your handling code here:
        this.txtAltura.setEnabled(true);
        this.txtComprimento.setEnabled(true);
    }//GEN-LAST:event_rbtTopBasedActionPerformed

    private void rbtNornalBasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNornalBasedActionPerformed
        // TODO add your handling code here:
        this.txtAltura.setEnabled(false);
        this.txtComprimento.setEnabled(false);
    }//GEN-LAST:event_rbtNornalBasedActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    /*
     * 
    public static void main(String args[]) {
        NewProjectModal.initWindow();
    }
    public static void initWindow(){

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProjectModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProjectModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProjectModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProjectModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewProjectModal dialog = new NewProjectModal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnPadrao;
    private javax.swing.JButton btnSelecionarRegioes;
    private javax.swing.JButton btnSelecionarVideo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jblProjeto;
    private javax.swing.JLabel lblBlur;
    private javax.swing.JLabel lblBlurValue;
    private javax.swing.JLabel lblCaminhoCompleto;
    private javax.swing.JLabel lblRegioes;
    private javax.swing.JLabel lblRegioesTotal;
    private javax.swing.JLabel lblSensibilidade;
    private javax.swing.JLabel lblSensibilidadeValue;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVideo;
    private javax.swing.ButtonGroup rbtGroupTipoSelecao;
    private javax.swing.JRadioButton rbtNornalBased;
    private javax.swing.JRadioButton rbtTopBased;
    private javax.swing.JSlider sliderBlur;
    private javax.swing.JSlider sliderSensibilidade;
    private javax.swing.JTextField tfNomeProjeto;
    private javax.swing.JTextField tfVideoFilename;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtComprimento;
    // End of variables declaration//GEN-END:variables
}
